# -*- coding: utf-8 -*-
"""Codigo_Prueba_Modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTcNl-mfRkiaoFYcN1wRK83peiNOcl94
"""

# -*- coding: utf-8 -*-
import sys
import io

"""
============================================================
  PROMO HUNTER — Modelo de Simulación
  Modelos y Simulación — Tercer Entregable
  Integrantes: Urbano, Ruiz, Arteaga, Sánchez
============================================================
  Arquitectura:
    1. Cadena de Markov Absorbente  → Embudo individual (publicación → compra)
    2. Cadena de Markov Ergódica    → Estado del canal (distribución estacionaria)
    3. Simulación Monte Carlo DES   → Convergencia y comparación de escenarios
    4. Análisis de Sensibilidad     → Robustez del modelo
============================================================
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

import seaborn as sns
from scipy.linalg import solve
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

np.random.seed(42)
plt.rcParams.update({'font.size': 10, 'font.family': 'DejaVu Sans'})
sns.set_theme(style="whitegrid")

# ─────────────────────────────────────────────────────────────
#  SECCIÓN 1: PARÁMETROS CALIBRADOS  (Datos reales ene-may 2026, 143 días)
# ─────────────────────────────────────────────────────────────

class P:
    """
    Parametros globales calibrados con datos REALES (ene-may 2026).
    Fuente: sim_embudo_completo.json  (Telegram API + Amazon Associates)
    Periodo: 143 dias, 21 097 posts, 11 tracking IDs.
    """
    # ── Datos reales del periodo completo ──────────────────────
    DIAS_DATOS        = 143
    POSTS_TOTALES     = 21_097
    VISTAS_TOTALES    = 6_613_127
    CLICS_TOTALES     = 96_507
    COMPRAS_TOTALES   = 6_027
    GANANCIAS_USD     = 3_149.42        # comisiones reales afiliado
    INGRESOS_USD      = 96_973.87       # revenue total Amazon

    # ── Parametros del embudo (calibrados) ─────────────────────
    # Etapa 1: Publicacion → Vista   LogNormal(mu, sigma)
    LOGNORM_MU        = 5.726           # media log-escala
    LOGNORM_SIGMA     = 0.201           # sd log-escala
    VISTAS_MEDIA      = 313.3           # E[X] = exp(mu + sigma^2/2)

    # Etapa 2: Vista → Clic   (CTR real medido)
    CTR               = 0.014593        # 1.46% — 1 de cada 68 vistas

    # Etapa 3: Clic → Compra  (Amazon Associates real)
    CR                = 0.0625          # 6.25% — 1 de cada 16 clics

    # Etapa 4: Compra
    COMISION_UNIT     = 0.52            # USD por compra (ganancia afiliado)
    INGRESO_UNIT      = 16.09           # USD por compra (revenue Amazon)
    TASA_DEVOLUCION   = 0.0169          # 1.69%

    # Variabilidad de CR por tracking ID (11 colaboradores)
    # Rango real: 4.21% - 8.27%  → modelado como Beta(alpha, beta)
    CR_TRACKING = {
        's73f45227-20':       0.0827,
        'elpromohunt0c-20':   0.0747,
        'krik0n-20':          0.0483,
        'koose-20':           0.0731,
        'brunardo-20':        0.0636,
        'opmilo21-20':        0.0623,
        'hnuol3820-20':       0.0421,
        'yennifer3606-20':    0.0606,
        'lmolartec3639-20':   0.0659,
        'chiriboga6490-20':   0.0522,
        'comardex-20':        0.0525,
    }
    CR_MED   = sum(CR_TRACKING.values()) / len(CR_TRACKING)  # ~6.25%
    CR_STD   = float(__import__('numpy').std(list(CR_TRACKING.values())))

    # ── Llegada de posts ───────────────────────────────────────
    PUBS_DIA          = 147.5           # media real (Poisson)

    # ── Tabla horaria REAL (sim_tabla_horaria.csv) ────────────
    # Fuente: 21 097 posts reales del canal, hora Colombia (UTC-5)
    # HALLAZGO: vistas/post es INVERSAMENTE proporcional al volumen
    # de publicaciones — menos posts por hora = mas visibilidad por post.

    # Matriz lambda REAL: posts esperados por (dia_semana x hora) — sim_lambda_matriz_dia_hora.csv
    # dia_num: 0=Lunes, 1=Martes, 2=Miercoles, 3=Jueves, 4=Viernes, 5=Sabado, 6=Domingo
    # HALLAZGO: Martes 0-4am tiene lambda alta (8.1, 2.6, 0.5) — turno nocturno atipico
    # El Jueves es el dia mas activo (~162 posts/dia), Lunes el mas bajo (~124)
    LAMBDA_MATRIZ = {
        0: {0:0.0,   1:0.0,   2:0.0,   3:0.049, 4:0.0,   6:0.049, 7:0.924, 8:4.424,
            9:7.389, 10:9.382,11:10.549,12:10.84,13:10.986,14:10.938,15:10.5,
            16:10.84,17:11.278,18:10.986,19:10.938,20:11.229,21:0.632,22:0.146,23:0.0},
        1: {0:8.118, 1:2.576, 2:0.486, 3:0.049, 4:0.778, 6:0.0,   7:0.826, 8:10.549,
            9:8.361, 10:9.382,11:10.792,12:12.104,13:12.25,14:12.347,15:12.007,
            16:12.299,17:12.347,18:12.201,19:12.056,20:12.444,21:0.632,22:0.049,23:0.0},
        2: {0:0.0,   1:0.0,   2:0.097, 3:0.0,   4:0.0,   6:0.0,   7:0.583, 8:5.736,
            9:7.875, 10:10.16,11:11.569,12:11.764,13:11.618,14:11.91,15:11.618,
            16:11.812,17:11.667,18:11.715,19:12.104,20:12.25,21:0.632,22:0.0,23:0.049},
        3: {0:0.0,   1:0.0,   2:0.0,   3:0.049, 4:0.0,   6:0.0,   7:0.194, 8:4.521,
            9:8.847, 10:11.521,11:13.319,12:13.951,13:13.903,14:14.049,15:14.097,
            16:14.049,17:13.757,18:14.146,19:13.903,20:14.194,21:0.583,22:0.049,23:0.097},
        4: {0:0.049, 1:0.049, 2:0.0,   3:0.0,   4:0.0,   6:0.0,   7:0.437, 8:4.472,
            9:8.118, 10:10.354,11:11.91,12:12.542,13:13.028,14:12.931,15:12.931,
            16:12.931,17:12.833,18:12.979,19:12.833,20:12.444,21:1.021,22:0.0,23:0.0},
        5: {0:0.0,   1:0.0,   2:0.0,   3:0.0,   4:0.097, 6:0.0,   7:0.681, 8:2.868,
            9:7.049, 10:10.792,11:11.132,12:12.979,13:12.59,14:12.833,15:13.076,
            16:12.396,17:12.299,18:12.785,19:12.153,20:11.91,21:0.486,22:0.0,23:0.0},
        6: {0:0.0,   1:0.0,   2:0.0,   3:0.0,   4:0.0,   6:0.049, 7:0.729, 8:4.083,
            9:5.639, 10:7.681,11:9.236,12:10.597,13:10.743,14:10.792,15:10.694,
            16:10.792,17:10.597,18:10.694,19:10.743,20:10.5,21:0.681,22:0.194,23:0.0},
    }
    # Lambda marginal por hora
    LAMBDA_HORA = {
        0:1.1667, 1:0.3750, 2:0.0833, 3:0.0069, 4:0.1250,
        5:0.0,    6:0.0139, 7:0.6250, 8:5.2292, 9:7.6111,
        10:9.8958,11:11.2153,12:12.1111,13:12.1597,14:12.2569,
        15:12.1319,16:12.1597,17:12.1111,18:12.2153,19:12.0972,
        20:12.1389,21:0.6528,22:0.0139,23:0.0,
    }

    # Vistas medias REALES por hora
    VISTAS_MEDIA_HORA = {
        0: 392.6,  1: 505.6,  2: 652.8,  3: 931.0,  4: 377.4,
        5: 313.3,  6: 438.0,  7: 388.6,  8: 339.1,  9: 324.2,
        10: 316.3, 11: 301.9, 12: 296.9, 13: 291.5, 14: 289.2,
        15: 287.9, 16: 291.9, 17: 296.9, 18: 307.6, 19: 330.0,
        20: 386.3, 21: 506.9, 22: 512.5, 23: 313.3,
    }

    # Factor multiplicador derivado de vistas reales / media global
    FACTOR_HORA = {h: v / 313.3 for h, v in VISTAS_MEDIA_HORA.items()}

    # ── Suscriptores (crecimiento real) ────────────────────────
    SUBS_INICIO       = 4_202           # 1 enero 2026
    SUBS_FIN          = 5_690           # 23 mayo 2026
    TASA_CRECIMIENTO  = (5_690 - 4_202) / (4_202 * 143)  # diaria ~0.0025

    # ── Categorías de producto (sim_tabla_categoria.csv) ──────
    CATEGORIAS = {
        'deportes':      {'pct_actual': 0.011, 'fwd_rate': 0.00143, 'vistas_media': 315.4, 'ctr_factor': 1.209},
        'hogar':         {'pct_actual': 0.163, 'fwd_rate': 0.00124, 'vistas_media': 312.6, 'ctr_factor': 1.048},
        'juguetes':      {'pct_actual': 0.034, 'fwd_rate': 0.00100, 'vistas_media': 312.8, 'ctr_factor': 0.845},
        'otra':          {'pct_actual': 0.328, 'fwd_rate': 0.00123, 'vistas_media': 311.9, 'ctr_factor': 1.039},
        'ropa':          {'pct_actual': 0.077, 'fwd_rate': 0.00135, 'vistas_media': 310.6, 'ctr_factor': 1.141},
        'salud/belleza': {'pct_actual': 0.081, 'fwd_rate': 0.00138, 'vistas_media': 307.6, 'ctr_factor': 1.166},
        'tecnologia':    {'pct_actual': 0.306, 'fwd_rate': 0.00102, 'vistas_media': 317.3, 'ctr_factor': 0.862},
    }

    MIX_OPTIMIZADO_C = {
        'deportes':      0.028,
        'hogar':         0.198,
        'juguetes':      0.052,
        'otra':          0.166,
        'ropa':          0.195,
        'salud/belleza': 0.205,
        'tecnologia':    0.155,
    }

    # ── Simulacion ─────────────────────────────────────────────
    DIAS_SIM          = 30
    N_SIMS            = 500
    CTR               = 0.014593
    CR                = 0.0625
    COMISION_UNIT     = 0.52

    HORARIO_BASE      = list(range(9, 22))
    HORARIO_OPTIM     = list(range(12, 24))
    HORARIO_SCORE     = [8, 9, 10, 11, 17, 18, 19, 20, 21]
    P_VISTA           = 313.3 / 4_946


# ─────────────────────────────────────────────────────────────
#  SECCIÓN 2: CADENA DE MARKOV ABSORBENTE — Embudo individual
# ─────────────────────────────────────────────────────────────

class MarkovEmbudo:
    NOMBRES = ['Publicado', 'Visto', 'Clic', 'Compra ✓', 'Perdido']

    def __init__(self, p_vista=None, ctr=None, cr=None):
        self.pv = p_vista if p_vista is not None else P.P_VISTA
        self.ctr = ctr if ctr is not None else P.CTR
        self.cr = cr if cr is not None else P.CR
        self._build()

    def _build(self):
        pv, ctr, cr = self.pv, self.ctr, self.cr
        self.M = np.array([
            [0, pv, 0, 0, 1 - pv],
            [0, 0, ctr, 0, 1 - ctr],
            [0, 0, 0, cr, 1 - cr],
            [0, 0, 0, 1, 0],
            [0, 0, 0, 0, 1],
        ])
        self.Q = self.M[:3, :3]
        self.R = self.M[:3, 3:]

    @property
    def N(self):
        return np.linalg.inv(np.eye(3) - self.Q)

    @property
    def B(self):
        return self.N @ self.R

    @property
    def prob_compra(self):
        return self.B[0, 0]

    def compras_esperadas_30d(self, n_subs=None, pubs_dia=None):
        n = n_subs or P.SUBS_INICIO
        pd_ = pubs_dia or P.PUBS_DIA
        return self.prob_compra * n * pd_ * P.DIAS_SIM

    def print_resumen(self):
        sep = "─" * 52
        print(f"\n{sep}")
        print("  MARKOV ABSORBENTE — Embudo de Conversión")
        print(sep)
        print(f"  P(compra | pub)   = {self.prob_compra:.6f}")
        print(sep)

# ─────────────────────────────────────────────────────────────
#  SECCIÓN 3: CADENA DE MARKOV ERGÓDICA — Estado del canal
# ─────────────────────────────────────────────────────────────

class MarkovCanal:
    ESTADOS = ['Bajo\n(<3%)', 'Normal\n(3-6%)', 'Alto\n(>6%)']

    def __init__(self, P_mat=None):
        if P_mat is None:
            self.P_mat = np.array([
                [0.50, 0.40, 0.10],
                [0.15, 0.65, 0.20],
                [0.05, 0.35, 0.60],
            ])
        else:
            self.P_mat = P_mat

    @property
    def pi(self):
        n = 3
        A = self.P_mat.T - np.eye(n)
        A[-1, :] = 1.0
        b = np.zeros(n)
        b[-1] = 1.0
        return solve(A, b)

    def freq_acumulada(self, n_dias=600):
        chain = [1]
        for _ in range(n_dias - 1):
            chain.append(np.random.choice(3, p=self.P_mat[chain[-1]]))
        freqs = np.zeros((n_dias, 3))
        for t in range(n_dias):
            for s in range(3):
                freqs[t, s] = (np.array(chain[:t + 1]) == s).mean()
        return freqs

    def print_resumen(self):
        print("\n  MARKOV ERGÓDICO — Estado del Canal")
        print(f"  π = {self.pi}")


# ─────────────────────────────────────────────────────────────
#  SECCIÓN 4: SIMULACIÓN MONTE CARLO
# ─────────────────────────────────────────────────────────────

def simular_periodo(horario: list, ctr=None, cr=None, comision=None) -> dict:
    ctr_    = ctr if ctr is not None else P.CTR
    com     = comision if comision is not None else P.COMISION_UNIT
    cr_vals = list(P.CR_TRACKING.values())

    registros = []
    for dia in range(P.DIAS_SIM):
        dia_semana = dia % 7
        subs       = int(P.SUBS_INICIO * (1 + P.TASA_CRECIMIENTO * dia))
        factor_subs = subs / P.SUBS_INICIO

        lambda_dia_hora = {h: P.LAMBDA_MATRIZ[dia_semana].get(h, 0) for h in horario if P.LAMBDA_MATRIZ[dia_semana].get(h, 0) > 0}

        for hora, lam in lambda_dia_hora.items():
            n_posts_hora = np.random.poisson(lam)
            if n_posts_hora == 0: continue

            v_base  = np.random.lognormal(P.LOGNORM_MU, P.LOGNORM_SIGMA, n_posts_hora)
            v_arr   = np.maximum(1, (v_base * P.FACTOR_HORA[hora] * factor_subs)).astype(int)

            cr_arr  = np.full(n_posts_hora, cr) if cr is not None else np.random.choice(cr_vals, n_posts_hora)
            clics_arr   = np.random.binomial(v_arr, ctr_)
            compras_arr = np.random.binomial(clics_arr, cr_arr)
            comis_arr   = compras_arr * com

            registros.append((v_arr.sum(), clics_arr.sum(), compras_arr.sum(), comis_arr.sum()))

    if not registros: return {'vistas': 0, 'clics': 0, 'compras': 0, 'ctr_real': 0, 'comisiones': 0.0}

    arr = np.array(registros)
    v_tot = arr[:, 0].sum()
    return {
        'vistas': int(v_tot), 'clics': int(arr[:, 1].sum()), 'compras': int(arr[:, 2].sum()),
        'ctr_real': arr[:, 1].sum() / v_tot if v_tot > 0 else 0, 'comisiones': round(arr[:, 3].sum(), 2),
    }

def monte_carlo(horario: list, n: int = None, label: str = '', ctr=None, cr=None) -> pd.DataFrame:
    n = n or P.N_SIMS
    resultados = [simular_periodo(horario, ctr=ctr, cr=cr) for _ in range(n)]
    df = pd.DataFrame(resultados)
    df['sim'] = range(n)
    df['escenario'] = label
    df['media_acum_com'] = df['comisiones'].expanding().mean()
    return df


# ─────────────────────────────────────────────────────────────
#  SECCIÓN 5: VISUALIZACIONES
# ─────────────────────────────────────────────────────────────

def plot_markov_embudo(emb):
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.set_title("Probabilidad de absorción")
    ax.bar(['Publicado', 'Visto', 'Clic'], emb.B[:, 0])
    return fig

def plot_funnel_counts(emb, subs=4946):
    fig, ax = plt.subplots(figsize=(8,4))

    etapas = [
        'Subscriptores',
        'Vistas',
        'Clicks',
        'Compras'
    ]

    valores = [
        subs,
        subs * emb.pv,
        subs * emb.pv * emb.ctr,
        subs * emb.pv * emb.ctr * emb.cr
    ]

    ax.plot(etapas, valores, marker='o', linewidth=2)

    ax.set_title("Embudo de conversión esperado")
    ax.set_ylabel("Cantidad esperada")

    for i, v in enumerate(valores):
        ax.text(i, v, f"{v:.2f}",
                ha='center', va='bottom')

    ax.grid(True)

    return fig

def plot_markov_canal(canal):
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.set_title("Distribución Estacionaria")
    ax.bar(canal.ESTADOS, canal.pi)
    return fig

def plot_convergencia_mc(df_a, df_b, df_c=None, df_d=None):
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(df_a['sim'], df_a['media_acum_com'], label="A")
    ax.plot(df_b['sim'], df_b['media_acum_com'], label="B")
    ax.legend()
    return fig

def plot_comparacion_escenarios(df_a, df_b, df_c=None, df_d=None):
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar(['A', 'B'], [df_a['comisiones'].mean(), df_b['comisiones'].mean()])
    return fig

def plot_sensibilidad(df_sens):
    fig, ax = plt.subplots(figsize=(6, 4))
    pivot = df_sens.pivot(index='factor_CR', columns='factor_CTR', values='com_media')
    sns.heatmap(pivot, annot=True, fmt='.0f', ax=ax)
    return fig


# ─────────────────────────────────────────────────────────────
#  SECCION 6: EJECUCION
# ─────────────────────────────────────────────────────────────

def main():
    emb = MarkovEmbudo()
    emb.print_resumen()
    canal = MarkovCanal()
    canal.print_resumen()

    df_a = monte_carlo(P.HORARIO_BASE,  label="A")
    df_b = monte_carlo(P.HORARIO_OPTIM, label="B")

    factor_mix_actual = sum(P.CATEGORIAS[c]['pct_actual']*P.CATEGORIAS[c]['ctr_factor'] for c in P.CATEGORIAS)
    factor_mix_optim  = sum(P.MIX_OPTIMIZADO_C[c]*P.CATEGORIAS[c]['ctr_factor'] for c in P.MIX_OPTIMIZADO_C)
    ctr_c = P.CTR * (factor_mix_optim / factor_mix_actual)

    df_c = monte_carlo(P.HORARIO_BASE,  label="C", ctr=ctr_c)
    df_d = monte_carlo(P.HORARIO_SCORE, label="D", ctr=ctr_c)

    import itertools
    filas = []
    for fc, fr in itertools.product([0.75, 1.0, 1.25], [0.75, 1.0, 1.25]):
        ctr_v = P.CTR * fc
        cr_v  = P.CR  * fr
        e_com = sum(P.LAMBDA_HORA[h] * 30 * P.VISTAS_MEDIA_HORA[h] * ctr_v * cr_v * P.COMISION_UNIT for h in P.HORARIO_BASE if P.LAMBDA_HORA.get(h,0)>0)
        filas.append({'factor_CTR': fc, 'factor_CR': fr, 'com_media': e_com})
    df_sens = pd.DataFrame(filas)

    print("\nGenerando gráficas...")
    #plot_markov_embudo(emb)
    plot_markov_canal(canal)
    plot_funnel_counts(emb)
    #plot_convergencia_mc(df_a, df_b, df_c, df_d)
    #plot_comparacion_escenarios(df_a, df_b, df_c, df_d)
    #plot_sensibilidad(df_sens)
    plt.show()
    
if __name__ == "__main__":
    main()
